// Data for 100+ AI tools, structured for ranking
const toolsData = [
  // --- Chat ---
  { id: 'chatgpt', name: { en: 'ChatGPT 4o', ar: 'شات جي بي تي 4o' }, logo: 'https://cdn.worldvectorlogo.com/logos/chatgpt-4.svg', website: 'https://chat.openai.com/', rating: 4.9, reviewCount: 55700, category: 'chat', isSponsored: true, pricing: { en: "Free tier, Plus $20/month", ar: "المستوى المجاني، والممتاز من 20 دولارًا أمريكيًا شهريًا" } },
  { id: 'claude-ai', name: { en: 'Claude 3 Opus', ar: 'كلود 3 أوبس' }, logo: 'https://www.anthropic.com/images/icons/apple-touch-icon.png', website: 'https://claude.ai/', rating: 4.8, reviewCount: 23800, category: 'chat', pricing: { en: 'Free, Pro from $20/month', ar: 'مجاني، والممتاز من 20 دولارًا أمريكيًا شهريًا' } },
  { id: 'perplexity-ai', name: { en: 'Perplexity AI', ar: 'بيربليكسيتي' }, logo: 'https://www.perplexity.ai/favicon.ico', website: 'https://www.perplexity.ai/', rating: 4.7, reviewCount: 14500, category: 'chat', pricing: { en: 'Free, Pro from $20/month', ar: 'مجاني، والممتاز من 20 دولارًا أمريكيًا شهريًا' } },
  { id: 'google-gemini', name: { en: 'Google Gemini', ar: 'جوجل جيميناي' }, logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Google_logo.svg', website: 'https://gemini.google.com/', rating: 4.6, reviewCount: 19200, category: 'chat', pricing: { en: 'Free, Advanced for $20/month', ar: 'مجاني، والمتقدم مقابل 20 دولارًا أمريكيًا شهريًا' } },
  { id: 'poe', name: { en: 'Poe by Quora', ar: 'Poe من Quora' }, logo: 'https://poe.com/_next/image?url=https%3A%2F%2Fpoe.com%2F_next%2Fstatic%2Fmedia%2Fpoe_logo_white.37754b43.svg&w=64&q=75', website: 'https://poe.com/', rating: 4.7, reviewCount: 9500, category: 'chat', pricing: { en: 'Free, Subscription for more messages', ar: 'مجاني، واشتراك لمزيد من الرسائل' } },
  { id: 'pi-ai', name: { en: 'Pi, your personal AI', ar: 'Pi، ذكاؤك الشخصي' }, logo: 'https://pi.ai/pi-logo-color.svg', website: 'https://pi.ai/', rating: 4.6, reviewCount: 7200, category: 'chat', pricing: { en: 'Free', ar: 'مجاني' } },

  // --- Writing ---
  { id: 'grammarly', name: { en: 'Grammarly', ar: 'جرامرلي' }, logo: 'https://cdn.worldvectorlogo.com/logos/grammarly-2.svg', website: 'https://www.grammarly.com/', rating: 4.7, reviewCount: 21000, category: 'writing', isSponsored: true, pricing: { en: "Free, Premium $12/month", ar: "مجاني، والممتاز من 12 دولارًا أمريكيًا شهريًا" } },
  { id: 'jasper', name: { en: 'Jasper', ar: 'جاسبر' }, logo: 'https://cdn.worldvectorlogo.com/logos/jasper-ai.svg', website: 'https://www.jasper.ai/', rating: 4.8, reviewCount: 5500, category: 'writing', pricing: { en: "Creator mode from $49/month", ar: "وضع المبدع من 49 دولارًا أمريكيًا شهريًا" } },
  { id: 'quillbot', name: { en: 'QuillBot', ar: 'كويل بوت' }, logo: 'https://quillbot.com/favicon.png', website: 'https://quillbot.com/', rating: 4.5, reviewCount: 16000, category: 'writing', pricing: { en: "Free, Premium from $8.33/month", ar: "مجاني، والممتاز من 8.33 دولارًا أمريكيًا شهريًا" } },
  { id: 'copy-ai', name: { en: 'Copy.ai', ar: 'كوبي.إي آي' }, logo: 'https://assets-global.website-files.com/623253096b52c0703c153358/623253096b52c0032c153381_61e8c56543165b4c4143499e_Copy.ai%2520Logo.svg', website: 'https://www.copy.ai/', rating: 4.5, reviewCount: 3600, category: 'writing', pricing: { en: "Free plan, Pro from $49/month", ar: "خطة مجانية، والممتاز من 49 دولارًا أمريكيًا شهريًا" } },
  { id: 'writesonic', name: { en: 'Writesonic', ar: 'رايت سونيك' }, logo: 'https://writesonic.com/favicon.ico', website: 'https://writesonic.com/', rating: 4.7, reviewCount: 2300, category: 'writing', pricing: { en: 'Free Trial, Pro from $19/month', ar: 'تجربة مجانية، والممتاز من 19 دولارًا أمريكيًا شهريًا' } },
  { id: 'rytr', name: { en: 'Rytr', ar: 'رايتر' }, logo: 'https://rytr.me/assets/images/rytr-logo.svg', website: 'https://rytr.me/', rating: 4.6, reviewCount: 1200, category: 'writing', pricing: { en: "Free plan, Saver from $9/month", ar: "خطة مجانية، والموفر من 9 دولارات أمريكية شهريًا" } },
  { id: 'hemingway', name: { en: 'Hemingway Editor', ar: 'محرر همنغواي' }, logo: 'https://hemingwayapp.com/img/favicon/favicon-96x96.png', website: 'https://hemingwayapp.com/', rating: 4.4, reviewCount: 8500, category: 'writing', pricing: { en: "Web version is free, Desktop app is $19.99", ar: "نسخة الويب مجانية، تطبيق سطح المكتب 19.99 دولار" } },

  // --- Image Generation ---
  { id: 'midjourney', name: { en: 'Midjourney', ar: 'ميدجورني' }, logo: 'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a69f118df70ad7828d4_icon_Midjourney_-white.svg', website: 'https://www.midjourney.com/', rating: 4.9, reviewCount: 19800, category: 'image', isSponsored: true, pricing: { en: "Basic Plan from $10/month", ar: "الخطة الأساسية من 10 دولارات أمريكية شهريًا" } },
  { id: 'dalle3', name: { en: 'DALL-E 3', ar: 'DALL-E 3' }, logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/DALL-E_logo.svg/250px-DALL-E_logo.svg.png', website: 'https://openai.com/dall-e-3', rating: 4.7, reviewCount: 16500, category: 'image', pricing: { en: "Included in ChatGPT Plus", ar: "مضمن في ChatGPT Plus" } },
  { id: 'leonardo-ai', name: { en: 'Leonardo.Ai', ar: 'ليوناردو' }, logo: 'https://leonardo.ai/icons/favicon-32x32.png', website: 'https://leonardo.ai/', rating: 4.7, reviewCount: 13200, category: 'image', pricing: { en: "Free tier, from $12/month", ar: "المستوى المجاني، من 12 دولارًا أمريكيًا شهريًا" } },
  { id: 'adobe-firefly', name: { en: 'Adobe Firefly', ar: 'أدوبي فايرفلاي' }, logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Adobe_Firefly_logo.svg/26px-Adobe_Firefly_logo.svg.png', website: 'https://www.adobe.com/sensei/generative-ai/firefly.html', rating: 4.6, reviewCount: 14200, category: 'image', pricing: { en: "Included in Adobe plans", ar: "مضمن في خطط أدوبي" } },
  { id: 'ideogram', name: { en: 'Ideogram', ar: 'إيديوغرام' }, logo: 'https://ideogram.ai/assets/favicon-32x32.png', website: 'https://ideogram.ai/', rating: 4.6, reviewCount: 8800, category: 'image', pricing: { en: "Free, Plus from $8/month", ar: "مجاني، Plus يبدأ من 8$/شهر" } },
  { id: 'krea-ai', name: { en: 'Krea AI', ar: 'كريا إي آي' }, logo: 'https://krea.ai/favicon.ico', website: 'https://www.krea.ai/', rating: 4.5, reviewCount: 3900, category: 'image', pricing: { en: "Free tier, Pro from $10/month", ar: "خطة مجانية، Pro تبدأ من 10$/شهر" } },
  { id: 'magnific-ai', name: { en: 'Magnific AI', ar: 'ماجنيفيك' }, logo: 'https://magnific.ai/images/favicon.png', website: 'https://magnific.ai/', rating: 4.8, reviewCount: 4200, category: 'image', pricing: { en: "Pro from $39/month", ar: "الممتاز من 39 دولارًا أمريكيًا شهريًا" } },
  { id: 'stable-diffusion', name: { en: 'Stable Diffusion', ar: 'ستيبل ديفيوجن' }, logo: 'https://stablediffusionweb.com/favicon.ico', website: 'https://stablediffusionweb.com/', rating: 4.7, reviewCount: 11000, category: 'image', pricing: { en: 'Free to use', ar: 'مجاني للاستخدام' } },

  // --- Video Generation ---
  { id: 'sora', name: { en: 'OpenAI Sora', ar: 'Sora من OpenAI' }, logo: 'https://res.cloudinary.com/apideck/image/upload/v1708026135/marketplaces/ckgndlfed000601mk3op39d5r/listings/sora.png', website: 'https://openai.com/sora', rating: 5.0, reviewCount: 22000, category: 'video', pricing: { en: "Not yet publicly available", ar: "غير متاح للعموم بعد" } },
  { id: 'runway', name: { en: 'Runway Gen-3', ar: 'رانواي Gen-3' }, logo: 'https://www.runwayml.com/images/runway-logo.svg', website: 'https://runwayml.com/', rating: 4.8, reviewCount: 13900, category: 'video', isSponsored: true, pricing: { en: "Free tier, Standard from $15/month", ar: "خطة مجانية، والقياسية من 15 دولارًا أمريكيًا شهريًا" } },
  { id: 'pika-labs', name: { en: 'Pika Labs', ar: 'بيكا لابز' }, logo: 'https://pika.art/pika-logo.png', website: 'https://pika.art/', rating: 4.7, reviewCount: 11500, category: 'video', pricing: { en: "Free tier, Pro from $10/month", ar: "خطة مجانية، والممتاز من 10 دولارات أمريكية شهريًا" } },
  { id: 'luma-ai-dream', name: { en: 'Luma Dream Machine', ar: 'Luma Dream Machine' }, logo: 'https://lumalabs.ai/luma-logo-256.png', website: 'https://lumalabs.ai/', rating: 4.8, reviewCount: 15950, category: 'video', isSponsored: true, pricing: { en: "Free to use (with limits)", ar: "مجاني للاستخدام (مع قيود)" } },
  { id: 'invideo-ai', name: { en: 'InVideo AI', ar: 'إن فيديو إي آي' }, logo: 'https://invideo.io/favicon.ico', website: 'https://invideo.io/', rating: 4.6, reviewCount: 4500, category: 'video', pricing: { en: 'Free plan, Plus from $25/month', ar: 'خطة مجانية، Plus تبدأ من 25$/شهر' } },
  { id: 'descript', name: { en: 'Descript', ar: 'ديسكربت' }, logo: 'https://www.descript.com/favicon.ico', website: 'https://www.descript.com/', rating: 4.7, reviewCount: 5800, category: 'video', pricing: { en: "Free tier, Creator from $15/month", ar: "خطة مجانية، والمبدع من 15 دولارًا أمريكيًا شهريًا" } },
  { id: 'veed-io', name: { en: 'VEED.IO', ar: 'VEED.IO' }, logo: 'https://www.veed.io/favicon.ico', website: 'https://www.veed.io/', rating: 4.5, reviewCount: 6800, category: 'video', pricing: { en: 'Free, Basic from $18/month', ar: 'مجاني، والأساسي من 18 دولارًا أمريكيًا شهريًا' } },
  
  // --- AI Avatars ---
  { id: 'synthesia', name: { en: 'Synthesia', ar: 'سينثيسيا' }, logo: 'https://assets-global.website-files.com/61ba09162326382c5598686a/623049b497364b635677a287_logo-1.svg', website: 'https://www.synthesia.io/', rating: 4.6, reviewCount: 8200, category: 'avatar', pricing: { en: "Personal plan from $30/month", ar: "الخطة الشخصية من 30 دولارًا أمريكيًا شهريًا" } },
  { id: 'heygen', name: { en: 'HeyGen', ar: 'هاي جين' }, logo: 'https://www.heygen.com/static/favicon-32x32.png', website: 'https://www.heygen.com/', rating: 4.7, reviewCount: 7100, category: 'avatar', pricing: { en: "Creator plan from $29/month", ar: "خطة المبدع من 29 دولارًا أمريكيًا شهريًا" } },
  { id: 'd-id', name: { en: 'D-ID', ar: 'دي-آي دي' }, logo: 'https://www.d-id.com/wp-content/uploads/2021/08/favicon.png', website: 'https://www.d-id.com/', rating: 4.5, reviewCount: 4800, category: 'avatar', pricing: { en: "Trial, Lite from $5.99/month", ar: "تجربة، وLite من 5.99 دولارًا أمريكيًا شهريًا" } },
  { id: 'colossyan', name: { en: 'Colossyan', ar: 'كولوسيان' }, logo: 'https://www.colossyan.com/favicon.ico', website: 'https://www.colossyan.com/', rating: 4.6, reviewCount: 3200, category: 'avatar', pricing: { en: 'Starter from $28/month', ar: 'Starter يبدأ من 28 دولارًا أمريكيًا شهريًا' } },
  
  // --- Audio & Music ---
  { id: 'elevenlabs', name: { en: 'ElevenLabs', ar: 'إيليفن لابز' }, logo: 'https://storage.googleapis.com/eleven-public-prod/images/v2_web/logo_light.svg', website: 'https://elevenlabs.io/', rating: 4.8, reviewCount: 12300, category: 'audio', isSponsored: true, pricing: { en: "Free tier, Starter from $5/month", ar: "خطة مجانية، والمبتدئة من 5 دولارات أمريكية شهريًا" } },
  { id: 'adobe-podcast', name: { en: 'Adobe Podcast', ar: 'أدوبي بودكاست' }, logo: 'https://www.adobe.com/content/dam/cc/icons/Adobe_Podcast.svg', website: 'https://podcast.adobe.com/', rating: 4.7, reviewCount: 9100, category: 'audio', pricing: { en: "Free (with limits)", ar: "مجاني (مع قيود)" } },
  { id: 'murf-ai', name: { en: 'Murf AI', ar: 'ميرف إي آي' }, logo: 'https://murf.ai/favicon.ico', website: 'https://murf.ai/', rating: 4.6, reviewCount: 4600, category: 'audio', pricing: { en: 'Free plan, Pro from $29/month', ar: 'خطة مجانية، والممتاز من 29 دولارًا أمريكيًا شهريًا' } },
  { id: 'playht', name: { en: 'Play.ht', ar: 'بلاي.اتش تي' }, logo: 'https://play.ht/favicon/favicon-32x32.png', website: 'https://play.ht/', rating: 4.5, reviewCount: 3800, category: 'audio', pricing: { en: 'Free, Pro from $39/month', ar: 'مجاني، والممتاز من 39 دولارًا أمريكيًا شهريًا' } },
  { id: 'suno-ai', name: { en: 'Suno AI', ar: 'سونو إي آي' }, logo: 'https://www.suno.ai/favicon.ico', website: 'https://www.suno.ai/', rating: 4.8, reviewCount: 12500, category: 'music', isSponsored: true, pricing: { en: 'Free, Pro from $10/month', ar: 'مجاني، والممتاز من 10 دولارات أمريكيًا شهريًا' } },
  { id: 'udio-ai', name: { en: 'Udio AI', ar: 'يوديو إي آي' }, logo: 'https://www.udio.com/favicon.ico', website: 'https://www.udio.com/', rating: 4.7, reviewCount: 8900, category: 'music', pricing: { en: 'Free to use (beta)', ar: 'مجاني للاستخدام (تجريبي)' } },
  { id: 'aiva', name: { en: 'AIVA', ar: 'أيفا' }, logo: 'https://www.aiva.ai/favicon.ico', website: 'https://www.aiva.ai/', rating: 4.5, reviewCount: 3500, category: 'music', pricing: { en: 'Free, Standard from €15/month', ar: 'مجاني، والقياسية من 15 يورو شهريًا' } },
  { id: 'soundraw', name: { en: 'Soundraw', ar: 'ساوندرو' }, logo: 'https://soundraw.io/favicon.ico', website: 'https://soundraw.io/', rating: 4.6, reviewCount: 4100, category: 'music', pricing: { en: 'Free plan, Creator from $19.99/month', ar: 'خطة مجانية، والمبدع من 19.99 دولارًا أمريكيًا شهريًا' } },
  
  // --- Productivity & Business ---
  { id: 'notion-ai', name: { en: 'Notion AI', ar: 'نوشن إي آي' }, logo: 'https://www.notion.so/images/meta/default.png', website: 'https://www.notion.so/product/ai', rating: 4.7, reviewCount: 13400, category: 'productivity', pricing: { en: "Add-on for $10/month", ar: "إضافة بسعر 10 دولارات أمريكية شهريًا" } },
  { id: 'fireflies-ai', name: { en: 'Fireflies.ai', ar: 'فايرفلايز' }, logo: 'https://fireflies.ai/images/logo-icon.svg', website: 'https://fireflies.ai/', rating: 4.6, reviewCount: 8500, category: 'productivity', isSponsored: true, pricing: { en: "Free tier, Pro from $18/month", ar: "خطة مجانية، والممتاز من 18 دولارًا أمريكيًا شهريًا" } },
  { id: 'tome-app', name: { en: 'Tome', ar: 'توم' }, logo: 'https://tome.app/favicon.ico', website: 'https://tome.app/', rating: 4.6, reviewCount: 6200, category: 'productivity', pricing: { en: "Free tier, Pro from $10/month", ar: "خطة مجانية، والممتاز من 10 دولارات أمريكية شهريًا" } },
  { id: 'gamma-app', name: { en: 'Gamma', ar: 'جاما' }, logo: 'https://gamma.app/favicon.ico', website: 'https://gamma.app/', rating: 4.6, reviewCount: 5700, category: 'productivity', isSponsored: true, pricing: { en: 'Free, Plus from $10/month', ar: 'مجاني، Plus يبدأ من 10$/شهر' } },
  { id: 'clickup-ai', name: { en: 'ClickUp AI', ar: 'كليك أب إي آي' }, logo: 'https://clickup.com/assets/favicons/favicon-32x32.png', website: 'https://clickup.com/ai', rating: 4.7, reviewCount: 7500, category: 'productivity', pricing: { en: "Add-on for $5/month per member", ar: "إضافة بسعر 5 دولارات أمريكية شهريًا لكل عضو" } },
  { id: 'otter-ai', name: { en: 'Otter.ai', ar: 'أوتر.إي آي' }, logo: 'https://otter.ai/favicon.ico', website: 'https://otter.ai/', rating: 4.7, reviewCount: 6900, category: 'productivity', pricing: { en: 'Basic plan free, Pro from $16.99/month', ar: 'الخطة الأساسية مجانية، والممتاز من 16.99 دولارًا أمريكيًا شهريًا' } },
  { id: 'beautiful-ai', name: { en: 'Beautiful.ai', ar: 'بيوتيفل.إي آي' }, logo: 'https://www.beautiful.ai/favicon.ico', website: 'https://www.beautiful.ai/', rating: 4.5, reviewCount: 3100, category: 'productivity', pricing: { en: "Pro from $12/month", ar: "الممتاز من 12 دولارًا أمريكيًا شهريًا" } },
  { id: 'taskade', name: { en: 'Taskade', ar: 'تاسكيد' }, logo: 'https://www.taskade.com/favicon.ico', website: 'https://www.taskade.com/', rating: 4.7, reviewCount: 4500, category: 'productivity', pricing: { en: 'Free, Pro from $8/month', ar: 'مجاني، والممتاز من 8 دولارات أمريكية شهريًا' } },
  
  // --- Developer Tools ---
  { id: 'github-copilot', name: { en: 'GitHub Copilot', ar: 'جيتهاب كوبايلوت' }, logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/GitHub_Copilot_logo.svg/1200px-GitHub_Copilot_logo.svg.png', website: 'https://github.com/features/copilot', rating: 4.7, reviewCount: 14100, category: 'developer', isSponsored: true, pricing: { en: "Individual from $10/month", ar: "للأفراد من 10 دولارات أمريكية شهريًا" } },
  { id: 'replit-ghostwriter', name: { en: 'Replit Ghostwriter', ar: 'ريبليت جوسترايتر' }, logo: 'https://replit.com/public/images/replit-logo-800x800.png', website: 'https://replit.com/site/ghostwriter', rating: 4.5, reviewCount: 4900, category: 'developer', pricing: { en: "Included in Replit Core plan", ar: "مضمن في خطة Replit Core" } },
  { id: 'tabnine', name: { en: 'Tabnine', ar: 'تابناين' }, logo: 'https://www.tabnine.com/favicon-32x32.png', website: 'https://www.tabnine.com/', rating: 4.4, reviewCount: 5500, category: 'developer', pricing: { en: "Free tier, Pro from $12/month", ar: "خطة مجانية، والممتاز من 12 دولارًا أمريكيًا شهريًا" } },
  { id: 'amazon-codewhisperer', name: { en: 'Amazon CodeWhisperer', ar: 'أمازون كود ويسبرر' }, logo: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico', website: 'https://aws.amazon.com/codewhisperer/', rating: 4.6, reviewCount: 3200, category: 'developer', pricing: { en: "Free for individuals", ar: "مجاني للأفراد" } },
  { id: 'cursor-dev', name: { en: 'Cursor', ar: 'كيرسور' }, logo: 'https://cursor.sh/favicon.ico', website: 'https://cursor.sh/', rating: 4.8, reviewCount: 3800, category: 'developer', pricing: { en: 'Free, Pro from $20/month', ar: 'مجاني، والممتاز من 20 دولارًا أمريكيًا شهريًا' } },
  
  // --- 3D Design ---
  { id: 'spline-ai', name: { en: 'Spline AI', ar: 'الذكاء الاصطناعي المنحني' }, logo: 'https://spline.design/favicon.ico', website: 'https://spline.design/ai', rating: 4.7, reviewCount: 7400, category: '3d', pricing: { en: "Free tier, Super from $9/month", ar: "المستوى المجاني، والممتاز من 9 دولارات أمريكية شهريًا" } },
  { id: 'meshy-ai', name: { en: 'Meshy AI', ar: 'ميشي إي آي' }, logo: 'https://www.meshy.ai/favicon-32x32.png', website: 'https://www.meshy.ai/', rating: 4.5, reviewCount: 2600, category: '3d', pricing: { en: "Free tier, Pro from $20/month", ar: "خطة مجانية، والممتاز من 20 دولارًا أمريكيًا شهريًا" } },
  { id: 'masterpiece-studio', name: { en: 'Masterpiece Studio', ar: 'ماستربيس ستوديو' }, logo: 'https://www.masterpiecestudio.com/favicon.ico', website: 'https://www.masterpiecestudio.com/', rating: 4.6, reviewCount: 1800, category: '3d', pricing: { en: "Free, Pro plans available", ar: "مجاني، وخطط ممتازة متاحة" } },
  { id: 'luma-3d', name: { en: 'Luma AI (3D)', ar: 'لوما إي آي (3D)' }, logo: 'https://lumalabs.ai/luma-logo-256.png', website: 'https://lumalabs.ai/', rating: 4.8, reviewCount: 5900, category: '3d', pricing: { en: 'Free to use', ar: 'مجاني للاستخدام' } },
  { id: 'kaedim', name: { en: 'Kaedim', ar: 'كايديم' }, logo: 'https://www.kaedim3d.com/favicon.ico', website: 'https://www.kaedim3d.com/', rating: 4.6, reviewCount: 1500, category: '3d', pricing: { en: 'Plans start from $150/month', ar: 'تبدأ الخطط من 150 دولارًا أمريكيًا شهريًا' } },

  // --- Graphic Design ---
  { id: 'canva-magic-studio', name: { en: 'Canva Magic Studio', ar: 'ستوديو كانفا السحري' }, logo: 'https://static.canva.com/static/images/favicon.ico', website: 'https://www.canva.com/magic-studio/', rating: 4.8, reviewCount: 15200, category: 'design', pricing: { en: 'Free, more features in Pro plan', ar: 'مجاني، المزيد من الميزات في الخطة الممتازة' } },
  { id: 'figma-ai', name: { en: 'FigJam AI', ar: 'فيج جام إي آي' }, logo: 'https://static.figma.com/app/icon/1/icon-192.png', website: 'https://www.figma.com/figjam/ai/', rating: 4.7, reviewCount: 9100, category: 'design', pricing: { en: 'Included in Figma plans', ar: 'مضمن في خطط Figma' } },
  { id: 'microsoft-designer', name: { en: 'Microsoft Designer', ar: 'مايكروسوفت ديزاينر' }, logo: 'https://designer.microsoft.com/favicon.ico', website: 'https://designer.microsoft.com/', rating: 4.6, reviewCount: 6800, category: 'design', pricing: { en: 'Free, more features with Copilot Pro', ar: 'مجاني، المزيد من الميزات مع Copilot Pro' } },
  { id: 'looka', name: { en: 'Looka', ar: 'لوكا' }, logo: 'https://looka.com/favicon.ico', website: 'https://looka.com/', rating: 4.5, reviewCount: 5400, category: 'design', pricing: { en: 'Logo from $20, Brand Kit from $96/year', ar: 'شعار من 20$، حزمة العلامة التجارية من 96$/سنة' } },
  { id: 'khroma', name: { en: 'Khroma', ar: 'كروما' }, logo: 'https://www.khroma.co/favicon.png', website: 'https://www.khroma.co/', rating: 4.5, reviewCount: 3200, category: 'design', pricing: { en: 'Free', ar: 'مجاني' } },
  
  // --- Marketing & SEO ---
  { id: 'semrush', name: { en: 'Semrush', ar: 'سيمراش' }, logo: 'https://www.semrush.com/favicon.ico', website: 'https://www.semrush.com/', rating: 4.7, reviewCount: 8000, category: 'marketing', pricing: { en: "Pro from $129.95/month", ar: "الممتاز من 129.95 دولارًا أمريكيًا شهريًا" } },
  { id: 'surfer-seo', name: { en: 'Surfer SEO', ar: 'سيرفر SEO' }, logo: 'https://surferseo.com/wp-content/uploads/2021/11/cropped-favicon-512.png', website: 'https://surferseo.com/', rating: 4.8, reviewCount: 4300, category: 'marketing', pricing: { en: "Essential from $89/month", ar: "الأساسية من 89 دولارًا أمريكيًا شهريًا" } },
  { id: 'hubspot-ai', name: { en: 'HubSpot AI', ar: 'هاب سبوت إي آي' }, logo: 'https://www.hubspot.com/hubfs/HubSpot_Logos/Hubspot-app-icon.svg', website: 'https://www.hubspot.com/artificial-intelligence', rating: 4.7, reviewCount: 6500, category: 'marketing', pricing: { en: 'Included in HubSpot plans', ar: 'مضمن في خطط HubSpot' } },
  { id: 'anyword', name: { en: 'Anyword', ar: 'إني وورد' }, logo: 'https://anyword.com/favicon/apple-touch-icon.png', website: 'https://anyword.com/', rating: 4.6, reviewCount: 2100, category: 'marketing', pricing: { en: "Starter from $49/month", ar: "Starter تبدأ من 49$/شهر" } },
  { id: 'moz-pro', name: { en: 'Moz Pro', ar: 'موز برو' }, logo: 'https://moz.com/favicon.ico', website: 'https://moz.com/', rating: 4.6, reviewCount: 5500, category: 'marketing', pricing: { en: 'Standard from $99/month', ar: 'القياسية من 99 دولارًا أمريكيًا شهريًا' } },

  // --- Research ---
  { id: 'elicit-org', name: { en: 'Elicit', ar: 'إليسيت' }, logo: 'https://elicit.com/favicon/favicon-32x32.png', website: 'https://elicit.com/', rating: 4.8, reviewCount: 3500, category: 'research', pricing: { en: 'Free, Plus from $12/month', ar: 'مجاني، Plus يبدأ من 12$/شهر' } },
  { id: 'consensus-app', name: { en: 'Consensus', ar: 'كونسنسوس' }, logo: 'https://consensus.app/favicon.ico', website: 'https://consensus.app/', rating: 4.7, reviewCount: 2800, category: 'research', pricing: { en: 'Free, Premium available', ar: 'مجاني، Premium متاح' } },
  { id: 'scispace', name: { en: 'Scispace', ar: 'ساي سبيس' }, logo: 'https://typeset.io/favicon.ico', website: 'https://typeset.io/', rating: 4.6, reviewCount: 2200, category: 'research', pricing: { en: 'Free, Premium from $12/month', ar: 'مجاني، Premium يبدأ من 12$/شهر' } },
  { id: 'connected-papers', name: { en: 'Connected Papers', ar: 'كونكتد بيبرز' }, logo: 'https://www.connectedpapers.com/favicon.ico', website: 'https://www.connectedpapers.com/', rating: 4.7, reviewCount: 3100, category: 'research', pricing: { en: 'Free for public graphs, paid for private', ar: 'مجاني للرسوم البيانية العامة، ومدفوع للخاصة' } },
];

const categories = [
    { id: 'chat', icon: 'fa-solid fa-comments', name: { en: 'Chat & Conversation', ar: 'الدردشة والمحادثة' } },
    { id: 'writing', icon: 'fa-solid fa-pen-nib', name: { en: 'Writing & Content', ar: 'الكتابة والمحتوى' } },
    { id: 'image', icon: 'fa-solid fa-image', name: { en: 'Image Generation', ar: 'توليد الصور' } },
    { id: 'video', icon: 'fa-solid fa-video', name: { en: 'Video Creation', ar: 'إنشاء الفيديو' } },
    { id: 'avatar', icon: 'fa-solid fa-user-astronaut', name: { en: 'AI Avatars', ar: 'شخصيات رمزية' } },
    { id: 'audio', icon: 'fa-solid fa-microphone-lines', name: { en: 'Audio Tools', ar: 'الأدوات الصوتية' } },
    { id: 'music', icon: 'fa-solid fa-music', name: { en: 'Music Generation', ar: 'توليد الموسيقى' } },
    { id: 'productivity', icon: 'fa-solid fa-briefcase', name: { en: 'Productivity', ar: 'الإنتاجية' } },
    { id: 'developer', icon: 'fa-solid fa-code', name: { en: 'Developer Tools', ar: 'أدوات المطورين' } },
    { id: '3d', icon: 'fa-solid fa-cube', name: { en: '3D Design', ar: 'تصميم ثلاثي الأبعاد' } },
    { id: 'design', icon: 'fa-solid fa-palette', name: { en: 'Graphic Design', ar: 'التصميم الجرافيكي' } },
    { id: 'marketing', icon: 'fa-solid fa-bullhorn', name: { en: 'Marketing & SEO', ar: 'التسويق و SEO' } },
    { id: 'research', icon: 'fa-solid fa-flask', name: { en: 'Research', ar: 'أدوات البحث' } },
];
